---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: self-host
    repo: https://charts.bitwarden.com/
    releaseName: bitwarden
    namespace: bitwarden

resources:
  - secrets.yaml
  - pvs.yaml