---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    releaseName: jellyfin
    namespace: jellyfin

resources:
  - helm/
  - ingressroute.yaml
  - certificate.yaml
  - pvs.yaml