---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rancher/local-path-provisioner
    repo: https://charts.rancher.io
    releaseName: local-path-provisioner
    namespace: local-path-provisioner