---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: local-path-provisioner
    repo: oci://dp.apps.rancher.io/charts/
    releaseName: local-path-provisioner
    namespace: local-path-provisioner